name: Build QMK firmware

on: 
  push:
    paths:
      - 'keyboards/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      # qmk_repo: qmk/qmk_firmware
      qmk_repo: jadewisemann/qmk_firmware
      qmk_ref: master

  release_history:
    name: 'Create Versioned Release'
    runs-on: ubuntu-latest
    needs: build
    if: always() && !cancelled()
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware_outputs
          merge-multiple: true

      - name: Generate Date Tag
        id: tag
        run: |
          export TZ='Asia/Seoul'

          echo "release_tag=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "release_date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}  # 태그: 20231125_123045
          name: Build ${{ steps.tag.outputs.release_date }} # 제목: Build 2023-11-25 12:30
          draft: false
          prerelease: false
          files: |
            firmware_outputs/**/*.hex
            firmware_outputs/**/*.bin
            firmware_outputs/**/*.uf2
            firmware_outputs/**/*.json
